name: Secret testing 

on:
  push

jobs:
  first-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking the content of Secret...
      run: |
        echo ${{ secrets.MINATO1 }}
        echo ${{secrets.MINATO1}} | sed 's/./& /g' 
